%% Strong field dom, strong fb 

clear;

feedPhaseMat = [1, 0; 0, 0.25];
feedAmpMat = [1, 0; 0, 0];


% For feedback phase continuation
setup_params_nonDim_CnstCplRatio(...
    'save',1, ...
    'alpha_par',0, ...
    'feed_ampli',0.5, ...
    'feed_ampliMatrix', feedAmpMat, ...
    'feed_phase',0, ...
    'feed_phaseMatrix', feedPhaseMat, ...
    'clear',0,...
    'J',560e-6,...
    'tau_fb', 0.8, ...
    'datadir_specific', ...
    '/home/bkmiller/qd-micropillar-laser-project/data_bimodal-qd-micropillars/strDomStrFbLowTau')

sweepSoln = sweeper(param.J.index, [60e-6, param.J.value], param, master_options);
dde23_soln = sweepSoln(end).timeSeries;


%%


% opt_inputs = { 'extra_condition', [1],'print_residual_info',[1] };
[branch_stst, nunst_branch_stst, ind_fold, ind_hopf] = ... 
    init_branch(funcs, ...
    dde23_soln.y(:,end), param.feed_phase.index, 500, param, ...
    'max_step',[param.feed_phase.index, (1)*pi/32], ...
    'minimal_real_part', -1, ...
    'halting_accuracy', 1e-12, ...
    'minimal_accuracy', 1e-10, ...
    'newton_max_iterations', 15, ...
    'reverse',1, ...
    master_options);
% , ...
%     'opt_inputs', opt_inputs);


%% ~300 for stab
vertBranch085 = pickAndSwitch(funcs, ...
    branch_stst, ...
    param.feed_ampli.index, ...
    250, ...
    param, ...
    'reverse',1, 'nunst_color', nunst_branch_stst, ...
    'point', 421);

plot_branch(vertBranch, param, ...
    'axes_indParam', [param.feed_phase.index, param.feed_ampli.index], ...
    'nunst_color', vertBranch.nunst)

save([master_options.datadir_specific,'vertBranch085.mat'],'vertBranch085');

%%
horizBranch015 = pickAndSwitch(funcs, ...
    vertBranch, ...
    param.feed_phase.index, ...
    350, ...
    param, ...
    'axes_indParam', [param.feed_phase.index, param.feed_ampli.index], ...
    'reverse',1, ...
    'point', 298);

plot_branch(horizBranch015, param, ...
    'axes_indParam', [param.feed_phase.index, param.feed_ampli.index], ...
    'nunst_color', horizBranch015.nunst)

save([master_options.datadir_specific,'horizBranch015.mat'],'horizBranch015');

%%

folds_horBrn015 = bifurFoldHopfMultiCreator( ...
    funcs, ...
    horizBranch015, ...
    param, ...
    folds_horBrn015.indFold, ...
    30);

save([master_options.datadir_specific,'folds_horBrn015.mat'],'folds_horBrn015');

%%
branchplot = figure;

for i = 1:numel(foldMulti)
    % Add each fold
    if isa(foldMulti(i).error,'double') && foldMulti(i).error == 0
        plot_branch(foldMulti(i), param, ...
            'add_2_gcf', 1, 'color','r');
    end
end