function [  ] = plot_bif_tree( tree, param, color )
%plot a tree

for i = 1:numel(tree)
    for j = 1:numel(tree{i})
        if tree{i}(j,1).error == 0
            plot_branch3(tree{i}(j), param, ...
                'add_2_gcf',1, ...
                'color', color, ...
                'axes_indParam', ...
                {tree{i}(j,1).parameter.free(1), ...
                tree{i}(j,1).parameter.free(2), ...
                'x1'}, ...
                'PlotStyle', { 'LineStyle', '-', 'Marker', '.' } );
        end
    end

end

