%% Setup General
clear;

% Laser/FB settings
current = 560e-6;
fbAmp = 0.2;
fbPhase = 0;
alpha_par = 0;
tau_fb_par = 0.1;

% feedback matrix settings
feedAmpMat = [1, 0; 0, 0];
feedPhaseMat = [1, 1; 1, 1];

% parameter setup
param = setup_params_nonDim_CnstCplRatio(...
    'save',0, ...
    'J', current, ...
    'feed_ampli',fbAmp, ...
    'feed_ampliMatrix', feedAmpMat, ...
    'feed_phase',fbPhase, ...
    'feed_phaseMatrix', feedPhaseMat, ...
    'tau_fb', tau_fb_par, ...
    'alpha_par',alpha_par, ...
    'clear',0,...
    'populate_wrkspc', 0);

% get funcs
funcs = set_biffuncs(feedPhaseMat, feedAmpMat);
opt_inputs = {'extra_condition',1,'print_residual_info',0, ...
              'plot', 0, 'plot_progress', 0};

% get starting points
weak_time_series = turn_on(param, [1e-9, 0, 1e-9, 0, 0]);
str_time_series = turn_on(param, [0.9^2, 0, 0.01, 0.6, 14]);

% steps
st_amp = steps_amp(param, ...
    'step', 0.002, ...
    'max_step', [param.feed_ampli.index,0.002, param.omega1.index,0.05], ...
    'max_bound', [param.feed_ampli.index, 0.5]);
st_phase = steps_phase(param, ...
    'max_step', [param.feed_phase.index,pi/25, param.omega1.index,0.05], ...
    'max_bound', [param.feed_phase.index, 5], ...
    'min_bound', [param.feed_phase.index, -5]);
st_bif = steps_bif(param, ...
    'step', 0.001, ...
    'max_step', [param.feed_ampli.index, 0.002, param.feed_phase.index,pi/32, param.omega1.index,0.01], ...
    'max_bound', [param.feed_ampli.index,0.75], ...
    'min_bound', [param.feed_ampli.index,-0.1]);

%% Amp at phase0
[famp_phase0,~] = SetupStst( ...
    funcs, ...
    'contpar',[param.feed_ampli.index, param.omega1.index], ...
    'corpar',[param.omega1.index],...
    'x', weak_time_series.y(:,end), ...
    'parameter', param.values(1:end-1),...
    opt_inputs{:},...
    st_amp{:});

famp_phase0 = bcont( funcs, famp_phase0, ...
                            2000, 2000 );
famp_phase0 = branch_stability(funcs, famp_phase0);

%% phase at amp 0.5
[phase_famp05,~] = SetupStst( ...
    funcs, ...
    'contpar',[param.feed_phase.index, param.omega1.index], ...
    'corpar',[param.omega1.index],...
    'x', famp_phase0.point(1).x, ...
    'parameter', famp_phase0.point(1).parameter,...
    opt_inputs{:},...
    st_phase{:});

phase_famp05 = bcont( funcs, phase_famp05, ...
                            2000, 2000 );
phase_famp05 = branch_stability(funcs, phase_famp05);

%% folds
folds = {};
relInds = phase_famp05.indFold(6:end-10);

for i = 1:numel(relInds)
    [foldfuncs, folds{i},~]=SetupRWFold( ...
        funcs, ...
        phase_famp05, ...
        relInds(i),...
        'contpar', ...
        [param.feed_phase.index, param.feed_ampli.index, param.omega1.index], ...
        'dir',param.feed_ampli.index, ...
        opt_inputs{:},...
        st_bif{:}); 

    folds{i} = bcont( foldfuncs, folds{i}, 50, 50 );
end

%% plot

plot_branch3( famp_phase0, ...
    param, ...
    'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
    'nunst_color', famp_phase0.nunst, ...
    'add_2_gcf', 1)

plot_branch3( phase_famp05, ...
    param, ...
    'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
    'nunst_color', phase_famp05.nunst, ...
    'add_2_gcf', 1)

for i = 1:numel(folds)
    plot_branch3( folds{i}, ...
    param, ...
    'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
    'color', 'r', ...
    'PlotStyle', { 'LineStyle', '-', 'Marker', '.' }, ...
    'add_2_gcf', 1)
end

