function [ stepbound ] = steps_phase( param )
%Return step bounds for phase
stepbound = { ...
    'step',pi/64, ...
    'max_step',...
    [param.feed_phase.index,pi/32, ...
    param.omega1.index,0.1], ...
    'newton_max_iterations',10, ...
    'max_bound',[param.feed_phase.index,10*pi], ...
    'min_bound', [param.feed_phase.index,-10*pi], ...
    'halting_accuracy',1e-10, ...
    'minimal_accuracy',1e-8};

end

