function [ stepbound ] = steps_amp( param, varargin )
%Return step bounds for amplitude
% options:
% step, newton_max_iterations, max_bound, min_bound, halting_accuracy, 
% minimal_accuracy

defaults = struct(...
    'step', 0.003, ...
    'max_step', ...
    [param.feed_ampli.index,0.006, ...
    param.omega1.index,0.1], ...
    'newton_max_iterations',10, ...
    'max_bound',[param.feed_ampli.index,2], ...
    'min_bound', [param.feed_ampli.index,-2], ...
    'halting_accuracy',1e-10, ...
    'minimal_accuracy',1e-8);

p = steps_parser(defaults, varargin{:});
options = p.Results;

stepbound = { ...
    'step', options.step, ...
    'max_step', options.max_step,...
    'newton_max_iterations', options.newton_max_iterations, ...
    'max_bound', options.max_bound, ...
    'min_bound', options.min_bound, ...
    'halting_accuracy', options.halting_accuracy, ...
    'minimal_accuracy', options.minimal_accuracy};

end

