function [ stepbound ] = steps_amp( param )
%Return step bounds for amplitude
stepbound = { ...
    'step',0.003, ...
    'max_step', ...
    [param.feed_ampli.index,0.006, ...
    param.omega1.index,0.1], ...
    'newton_max_iterations',10, ...
    'max_bound',[param.feed_ampli.index,2], ...
    'min_bound', [param.feed_ampli.index,-2], ...
    'halting_accuracy',1e-10, ...
    'minimal_accuracy',1e-8};

end

