%% Setup General
clear;

% Laser/FB settings
current = 560e-6;
fbAmp = 0.2;
fbPhase = 0;
alpha_par = 0;
tau_fb_par = 0.8;

% feedback matrix settings
feedAmpMat = [1, 0; 0, 0];
feedPhaseMat = [1, 1; 1, 1];

% parameter setup
param = setup_params_nonDim_CnstCplRatio(...
    'save',0, ...
    'J', current, ...
    'feed_ampli',fbAmp, ...
    'feed_ampliMatrix', feedAmpMat, ...
    'feed_phase',fbPhase, ...
    'feed_phaseMatrix', feedPhaseMat, ...
    'tau_fb', tau_fb_par, ...
    'alpha_par',alpha_par, ...
    'clear',0,...
    'populate_wrkspc', 0);

% get funcs
funcs = set_biffuncs(feedPhaseMat, feedAmpMat);
opt_inputs = {'extra_condition',1,'print_residual_info',0, ...
              'plot', 0, 'plot_progress', 0};

% get starting points
weak_time_series = turn_on(param, [1e-9, 0, 1e-9, 0, 0]);
str_time_series = turn_on(param, [0.9^2, 0, 0.01, 0.6, 14]);

% steps
st_amp = steps_amp(param);
st_phase = steps_phase(param, ...
    'max_step', [param.feed_phase.index,pi/16, param.omega1.index,0.1]);
st_bif = steps_bif(param, ...
    'max_bound', [param.feed_ampli.index,0.5], ...
    'min_bound', [param.feed_ampli.index,-0.1]);

%% WeakDom phase
[init_phase_WeakDom,~] = SetupStst( ...
    funcs, ...
    'contpar',[param.feed_phase.index, param.omega1.index], ...
    'corpar',[param.omega1.index],...
    'x', weak_time_series.y(:,end), ...
    'parameter',param.values(1:end-1),...
    opt_inputs{:},...
    st_phase{:});

init_phase_WeakDom = bcont( funcs, init_phase_WeakDom, ...
                            200, 200 );
init_phase_WeakDom = branch_stability(funcs, init_phase_WeakDom);

% WeakDom fold
[foldfuncs,fold_v_Weak,~]=SetupRWFold( ...
    funcs, ...
    init_phase_WeakDom, ...
    init_phase_WeakDom.indFold(1),...
    'contpar', ...
    [param.feed_phase.index, param.feed_ampli.index, param.omega1.index], ...
    'dir',param.feed_ampli.index, ...
    opt_inputs{:},...
    st_bif{:}); 

fold_v_Weak = bcont( foldfuncs, fold_v_Weak, 50, 50 );

%% WeakDom amp, unstable, after fold, between v
% We get this from the stable branch
ind_midv_weak_unstable = round((init_phase_WeakDom.indFold(1) + ...
                            init_phase_WeakDom.indFold(2))/2);
% [ampWeakDom_unst,~] = SetupStst( ...
%     funcs, ...
%     'contpar',[param.feed_ampli.index, param.omega1.index], ...
%     'corpar',[param.omega1.index],...
%     'x', init_phase_WeakDom.point(ind_mid_v_unstable).x, ...
%     'parameter',init_phase_WeakDom.point(ind_mid_v_unstable).parameter,...
%     opt_inputs{:},...
%     st_amp{:});
% 
% ampWeakDom_unst = bcont( funcs, ampWeakDom_unst, ...
%                             50, 400 );
% ampWeakDom_unst = branch_stability(funcs, ampWeakDom_unst);

% Find similar phase (midpoint of the unstable section between v)
for i = 1:numel(init_phase_WeakDom.nunst)
    if (0.1 > ...
        abs(init_phase_WeakDom.point(i).parameter(param.feed_phase.index) - ...
        init_phase_WeakDom.point(ind_midv_weak_unstable).parameter(param.feed_phase.index)) && ...
        init_phase_WeakDom.nunst(i) == 0)
        ind_midv_weak_stable = i;
        break
    end
end

%% WeakDom amp, stable, before fold, between v
[ampWeakDom_stab1,~] = SetupStst( ...
    funcs, ...
    'contpar',[param.feed_ampli.index, param.omega1.index], ...
    'corpar',[param.omega1.index],...
    'x', init_phase_WeakDom.point(ind_midv_weak_stable).x, ...
    'parameter',init_phase_WeakDom.point(ind_midv_weak_stable).parameter,...
    opt_inputs{:},...
    st_amp{:});

ampWeakDom_stab1 = bcont( funcs, ampWeakDom_stab1, ...
                            200, 200 );
ampWeakDom_stab1 = branch_stability(funcs, ampWeakDom_stab1);

% zig zags
[ampWeakDom_stab2,~] = SetupStst( ...
    funcs, ...
    'contpar',[param.feed_ampli.index, param.omega1.index], ...
    'corpar',[param.omega1.index],...
    'x', init_phase_WeakDom.point(ind_midv_weak_stable + 4).x, ...
    'parameter',init_phase_WeakDom.point(ind_midv_weak_stable + 4).parameter,...
    opt_inputs{:},...
    st_amp{:});

ampWeakDom_stab2 = bcont( funcs, ampWeakDom_stab2, ...
                            200, 200 );
ampWeakDom_stab2 = branch_stability(funcs, ampWeakDom_stab2);

% Stuck in a loop
[ampWeakDom_stab3,~] = SetupStst( ...
    funcs, ...
    'contpar',[param.feed_ampli.index, param.omega1.index], ...
    'corpar',[param.omega1.index],...
    'x', init_phase_WeakDom.point(ind_midv_weak_stable + 4).x, ...
    'parameter',init_phase_WeakDom.point(ind_midv_weak_stable + 4).parameter,...
    opt_inputs{:},...
    st_amp{:});

ampWeakDom_stab3 = bcont( funcs, ampWeakDom_stab3, ...
                            200, 200 );
ampWeakDom_stab3 = branch_stability(funcs, ampWeakDom_stab3);

% You should plot the fold bifurcations from the zig zag branch and see.

%% StrDom phase
[init_phase_StrDom,~] = SetupStst( ...
    funcs, ...
    'contpar',[param.feed_phase.index, param.omega1.index], ...
    'corpar',[param.omega1.index],...
    'x', str_time_series.y(:,end), ...
    'parameter',param.values(1:end-1),...
    opt_inputs{:},...
    st_phase{:});

init_phase_StrDom = bcont( funcs, init_phase_StrDom, ...
                            200, 200 );
init_phase_StrDom = branch_stability(funcs, init_phase_StrDom);

% StrDom fold
[foldfuncs,fold_v_Str,~]=SetupRWFold( ...
    funcs, ...
    init_phase_StrDom, ...
    init_phase_StrDom.indFold(1),...
    'contpar', ...
    [param.feed_phase.index, param.feed_ampli.index, param.omega1.index], ...
    'dir',param.feed_ampli.index, ...
    opt_inputs{:},...
    st_bif{:}); 

fold_v_Str = bcont( foldfuncs, fold_v_Str, 50, 50 );

%% StrDom amp between v (start stable)
% This one ends up just staying stable and getting stuck near zero
% ind_midv_str_unstable = round((init_phase_StrDom.indFold(1) + ...
%                             init_phase_StrDom.indFold(2))/2);
% for i = 1:numel(init_phase_StrDom.nunst)
%     if (0.1 > ...
%         abs(init_phase_StrDom.point(i).parameter(param.feed_phase.index) - ...
%         init_phase_StrDom.point(ind_midv_str_unstable).parameter(param.feed_phase.index)) && ...
%         init_phase_StrDom.nunst(i) == 0)
%         ind_midv_str_stable = i;
%         break
%     end
% end
% 
% [ampStrDom,~] = SetupStst( ...
%     funcs, ...
%     'contpar',[param.feed_ampli.index, param.omega1.index], ...
%     'corpar',[param.omega1.index],...
%     'x', init_phase_StrDom.point(ind_midv_str_stable).x, ...
%     'parameter',init_phase_StrDom.point(ind_midv_str_stable).parameter,...
%     opt_inputs{:},...
%     st_amp{:});
% 
% ampStrDom = bcont( funcs, ampStrDom, ...
%                             20, 200 );
% ampStrDom = branch_stability(funcs, ampStrDom);


%% plot Weak Phase
plot_branch3( init_phase_WeakDom, ...
    param, ...
    'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
    'nunst_color', init_phase_WeakDom.nunst )

%% plot folds weak
plot_branch3( fold_v_Weak, ...
    param, ...
    'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
    'color', 'r', ...
    'PlotStyle', { 'LineStyle', '-', 'Marker', '.' }, ...
    'add_2_gcf', 1)

%% Plot weak amp from unst and stab
plot_branch3( ampWeakDom_stab1, ...
    param, ...
    'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
    'nunst_color', ampWeakDom_stab1.nunst, ...
    'add_2_gcf', 1)

% plot_branch3( ampWeakDom_unst, ...
%     param, ...
%     'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
%     'nunst_color', ampWeakDom_unst.nunst, ...
%     'add_2_gcf', 1)

%% plot Strong Phase
plot_branch3( init_phase_StrDom, ...
    param, ...
    'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
    'nunst_color', {init_phase_StrDom.nunst, 5}, ...
    'add_2_gcf', 1)

%% plot folds strong
plot_branch3( fold_v_Str, ...
    param, ...
    'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
    'color', 'r', ...
    'PlotStyle', { 'LineStyle', '-', 'Marker', '.' }, ...
    'add_2_gcf', 1)

% %% Plot strong amp stab 
% plot_branch3( ampStrDom, ...
%     param, ...
%     'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
%     'nunst_color', ampStrDom.nunst, ...
%     'add_2_gcf', 1)