%% Setup General
clear;

% Laser/FB settings
current = 560e-6;
fbAmp = 0.2;
fbPhase = 0;
alpha_par = 0;
tau_fb_par = 0.8;

% feedback matrix settings
feedAmpMat = [1, 0; 0, 0];
feedPhaseMat = [1, 1; 1, 1];

% parameter setup
param = setup_params_nonDim_CnstCplRatio(...
    'save',0, ...
    'J', current, ...
    'feed_ampli',fbAmp, ...
    'feed_ampliMatrix', feedAmpMat, ...
    'feed_phase',fbPhase, ...
    'feed_phaseMatrix', feedPhaseMat, ...
    'tau_fb', tau_fb_par, ...
    'alpha_par',alpha_par, ...
    'clear',0,...
    'populate_wrkspc', 0);

% get funcs
funcs = set_biffuncs(feedPhaseMat, feedAmpMat);
opt_inputs = {'extra_condition',1,'print_residual_info',0, ...
              'plot', 0, 'plot_progress', 0};

% get starting points
weak_time_series = turn_on(param, [1e-9, 0, 1e-9, 0, 0]);
str_time_series = turn_on(param, [0.9^2, 0, 0.01, 0.6, 14]);

% steps
st_amp = steps_amp(param);
st_phase = steps_phase(param, ...
    'max_step', [param.feed_phase.index,pi/16, param.omega1.index,0.1]);
st_bif = steps_bif(param, ...
    'step', 0.001, ...
    'max_step', [param.feed_ampli.index, 0.002, param.feed_phase.index,pi/32, param.omega1.index,0.01], ...
    'max_bound', [param.feed_ampli.index,0.75], ...
    'min_bound', [param.feed_ampli.index,-0.1]);

%% WeakDom phase
[init_phase_WeakDom,~] = SetupStst( ...
    funcs, ...
    'contpar',[param.feed_phase.index, param.omega1.index], ...
    'corpar',[param.omega1.index],...
    'x', weak_time_series.y(:,end), ...
    'parameter',param.values(1:end-1),...
    opt_inputs{:},...
    st_phase{:});

init_phase_WeakDom = bcont( funcs, init_phase_WeakDom, ...
                            200, 200 );
init_phase_WeakDom = branch_stability(funcs, init_phase_WeakDom);

% WeakDom fold
[foldfuncs,fold_v_Weak,~]=SetupRWFold( ...
    funcs, ...
    init_phase_WeakDom, ...
    init_phase_WeakDom.indFold(1),...
    'contpar', ...
    [param.feed_phase.index, param.feed_ampli.index, param.omega1.index], ...
    'dir',param.feed_ampli.index, ...
    opt_inputs{:},...
    st_bif{:}); 

fold_v_Weak = bcont( foldfuncs, fold_v_Weak, 50, 50 );

%% WeakDom amp, unstable, after fold, between v
% We get this from the stable branch
ind_midv_weak_unstable = round((init_phase_WeakDom.indFold(1) + ...
                            init_phase_WeakDom.indFold(2))/2);
% [ampWeakDom_unst,~] = SetupStst( ...
%     funcs, ...
%     'contpar',[param.feed_ampli.index, param.omega1.index], ...
%     'corpar',[param.omega1.index],...
%     'x', init_phase_WeakDom.point(ind_mid_v_unstable).x, ...
%     'parameter',init_phase_WeakDom.point(ind_mid_v_unstable).parameter,...
%     opt_inputs{:},...
%     st_amp{:});
% 
% ampWeakDom_unst = bcont( funcs, ampWeakDom_unst, ...
%                             50, 400 );
% ampWeakDom_unst = branch_stability(funcs, ampWeakDom_unst);

% Find similar phase (midpoint of the unstable section between v)
for i = 1:numel(init_phase_WeakDom.nunst)
    if (0.1 > ...
        abs(init_phase_WeakDom.point(i).parameter(param.feed_phase.index) - ...
        init_phase_WeakDom.point(ind_midv_weak_unstable).parameter(param.feed_phase.index)) && ...
        init_phase_WeakDom.nunst(i) == 0)
        ind_midv_weak_stable = i;
        break
    end
end

%% WeakDom amp, stable, before fold, between v
arr = [-4, 0, 4];
ampWeakDoms = cell(1, numel(arr));

for i = 1:3
    [ampWeakDom,~] = SetupStst( ...
    funcs, ...
    'contpar',[param.feed_ampli.index, param.omega1.index], ...
    'corpar',[param.omega1.index],...
    'x', init_phase_WeakDom.point(ind_midv_weak_stable + arr(i)).x, ...
    'parameter',init_phase_WeakDom.point(ind_midv_weak_stable + arr(i)).parameter,...
    opt_inputs{:},...
    st_amp{:});
    ampWeakDom = bcont( funcs, ampWeakDom, ...
                                200, 200 );
    ampWeakDom = branch_stability(funcs, ampWeakDom);
    
    ampWeakDoms{i} = ampWeakDom;
end

%% folds from middle ampWeakDom branch
inds = ampWeakDoms{2}.indFold(2:end-1);
foldsFromMidAmpWeakDom = cell(1, numel(inds));

for i = 1:numel(inds)
    % StrDom fold
    [foldfuncs,foldsFromMidAmpWeakDom{i},~]=SetupRWFold( ...
        funcs, ...
        ampWeakDoms{2}, ...
        inds(i),...
        'contpar', ...
        [param.feed_phase.index, param.feed_ampli.index, param.omega1.index], ...
        'dir',param.feed_ampli.index, ...
        opt_inputs{:},...
        st_bif{:}); 

    foldsFromMidAmpWeakDom{i} = bcont( foldfuncs, foldsFromMidAmpWeakDom{i}, 50, 50 );
end

%% phases below v
inds = branch_pts_near_param(ampWeakDoms{1}, param.feed_ampli.index, 0, 0.004);
inds = [inds(find(ampWeakDoms{1}.nunst(inds)==1, 1)), ...
        inds(find(ampWeakDoms{1}.nunst(inds)==0, 1))];
phases_below_v_low = cell(1,numel(inds));

for i = 1:numel(phases_below_v_low)
    [phases_below_v_low{i},~] = SetupStst( ...
        funcs, ...
        'contpar',[param.feed_phase.index, param.omega1.index], ...
        'corpar',[param.omega1.index],...
        'x', ampWeakDoms{1}.point(inds(i)).x, ...
        'parameter',ampWeakDoms{1}.point(inds(i)).parameter,...
        opt_inputs{:},...
        st_phase{:});

    phases_below_v_low{i} = bcont( funcs, phases_below_v_low{i}, ...
                                50, 50 );
    phases_below_v_low{i} = branch_stability(funcs, phases_below_v_low{i});
end


%% StrDom phase
[init_phase_StrDom,~] = SetupStst( ...
    funcs, ...
    'contpar',[param.feed_phase.index, param.omega1.index], ...
    'corpar',[param.omega1.index],...
    'x', str_time_series.y(:,end), ...
    'parameter',param.values(1:end-1),...
    opt_inputs{:},...
    st_phase{:});

init_phase_StrDom = bcont( funcs, init_phase_StrDom, ...
                            200, 200 );
init_phase_StrDom = branch_stability(funcs, init_phase_StrDom);

% StrDom fold
[foldfuncs,fold_v_Str,~]=SetupRWFold( ...
    funcs, ...
    init_phase_StrDom, ...
    init_phase_StrDom.indFold(1),...
    'contpar', ...
    [param.feed_phase.index, param.feed_ampli.index, param.omega1.index], ...
    'dir',param.feed_ampli.index, ...
    opt_inputs{:},...
    st_bif{:}); 

fold_v_Str = bcont( foldfuncs, fold_v_Str, 50, 50 );

%% StrDom amp between v (start stable)
ind_midv_str_unstable = round((init_phase_StrDom.indFold(1) + ...
                                init_phase_StrDom.indFold(2))/2);
[ampStrDom,~] = SetupStst( ...
        funcs, ...
        'contpar',[param.feed_ampli.index, param.omega1.index], ...
        'corpar',[param.omega1.index],...
        'x', init_phase_StrDom.point(ind_midv_str_unstable + arr(end)).x, ...
        'parameter',init_phase_StrDom.point(ind_midv_str_unstable + arr(end)).parameter,...
        opt_inputs{:},...
        st_amp{:});

ampStrDom = bcont( funcs, ampStrDom, ...
                            200, 60 );
ampStrDom = branch_stability(funcs, ampStrDom);

if 0
    % It starts at a negative omega and turns around. Goes to really high
    % amp
    ind_midv_str_unstable = round((init_phase_StrDom.indFold(1) + ...
                                init_phase_StrDom.indFold(2))/2);
    for i = 1:numel(init_phase_StrDom.nunst)
        if (0.1 > ...
            abs(init_phase_StrDom.point(i).parameter(param.feed_phase.index) - ...
            init_phase_StrDom.point(ind_midv_str_unstable).parameter(param.feed_phase.index)) && ...
            init_phase_StrDom.nunst(i) == 0)
            ind_midv_str_stable = i;
            break
        end
    end

    [ampStrDom,~] = SetupStst( ...
        funcs, ...
        'contpar',[param.feed_ampli.index, param.omega1.index], ...
        'corpar',[param.omega1.index],...
        'x', init_phase_StrDom.point(ind_midv_str_stable).x, ...
        'parameter',init_phase_StrDom.point(ind_midv_str_stable).parameter,...
        opt_inputs{:},...
        'plot_progress', 1, ...
        'plot', 1, ...
        st_amp{:});

    ampStrDom = bcont( funcs, ampStrDom, ...
                                100, 300 );
    ampStrDom = branch_stability(funcs, ampStrDom);

    % Plot strong amp stab 
    plot_branch3( ampStrDom, ...
        param, ...
        'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
        'nunst_color', ampStrDom.nunst, ...
        'add_2_gcf', 1)
end

%% Phases along StrDom Amp branch connecting StrDom and WeakDom
arr = [1, find(ampStrDom.nunst==2, 1), numel(ampStrDom.nunst)/2, 0];

% find one with phase close to special number 0.34
search = find(ampStrDom.nunst==2);
matches = [];
for i = 1:numel(search)
    v = ampStrDom.point(search(i)).parameter(param.feed_ampli.index);
    if abs(0.34 - v) < 0.01
        matches(end+1) = search(i);
    end
end
arr(end) = matches(end);

phaseAlongStrDoms = cell(1, numel(arr));
do_gcf = [0, 1, 1, 1];

for i = [3, 4] % 1:numel(arr)
    [phaseAlongStrDom,~] = SetupStst( ...
    funcs, ...
    'contpar',[param.feed_phase.index, param.omega1.index], ...
    'corpar',[param.omega1.index],...
    'x', ampStrDom.point(arr(i)).x, ...
    'parameter',ampStrDom.point(arr(i)).parameter,...
    opt_inputs{:},...
    st_phase{:});

    phaseAlongStrDom = bcont( funcs, phaseAlongStrDom, ...
                                200, 200 );
    phaseAlongStrDom = branch_stability(funcs, phaseAlongStrDom);
    phaseAlongStrDoms{i} = phaseAlongStrDom;
    
    
%     plot_branch3( phaseAlongStrDom, ...
%     param, ...
%     'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
%     'nunst_color', phaseAlongStrDom.nunst, ...
%     'add_2_gcf', do_gcf(i))
end
% 1 has potentially new fold bifurcations and a wider structure
%   It's just more of the vs
% 2 has stable solutions!!! :O
%   These connect to the StrDom McDonalds shape
% 3 has a loop-da-loop structure but is unstable
% 4 tried to find loop-da-loop in special area

% %% 1 follow the folds in the StrongDom similar area to WeakDom
% inds = phaseAlongStrDoms{1}.indFold;
% foldsFromStrDomNearlyWeakDom = cell(1, numel(inds));
% 
% for i = 1:numel(inds)
%     % StrDom fold
%     [foldfuncs,foldsFromStrDomNearlyWeakDom{i},~]=SetupRWFold( ...
%         funcs, ...
%         phaseAlongStrDoms{1}, ...
%         phaseAlongStrDoms{1}.indFold(i),...
%         'contpar', ...
%         [param.feed_phase.index, param.feed_ampli.index, param.omega1.index], ...
%         'dir',param.feed_ampli.index, ...
%         opt_inputs{:},...
%         st_bif{:}); 
% 
%     foldsFromStrDomNearlyWeakDom{i} = bcont( foldfuncs, foldsFromStrDomNearlyWeakDom{i}, 50, 50 );
%     
%     plot_branch3( foldsFromStrDomNearlyWeakDom{i}, ...
%         param, ...
%         'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
%         'color', 'r', ...
%         'PlotStyle', { 'LineStyle', '-', 'Marker', '.' }, ...
%         'add_2_gcf', 1)
% end


% %% 2 follow those stable solutions in amplitude
% ind = find(phaseAlongStrDoms{2}.nunst==0);
% ind = ind(round(end/2));
% 
% [unlikelyStableMidDom,~] = SetupStst( ...
%         funcs, ...
%         'contpar',[param.feed_ampli.index, param.omega1.index], ...
%         'corpar',[param.omega1.index],...
%         'x', phaseAlongStrDoms{2}.point(ind).x, ...
%         'parameter',phaseAlongStrDoms{2}.point(ind).parameter,...
%         opt_inputs{:},...
%         st_amp{:});
% 
% unlikelyStableMidDom = bcont( funcs, unlikelyStableMidDom, ...
%                             200, 200 );
% unlikelyStableMidDom = branch_stability(funcs, unlikelyStableMidDom);


%% save?
if 1
    % save location
    datadir = strcat(data_directory(), 'specific_bifurcations/');
    while isdir(datadir) == 0
        mkdir(datadir);
    end
    
    save(strcat(datadir, 'vfolds'))
end

%% plot Weak Phase
plot_branch3( init_phase_WeakDom, ...
    param, ...
    'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
    'nunst_color', init_phase_WeakDom.nunst )

%% plot Strong Phase
plot_branch3( init_phase_StrDom, ...
    param, ...
    'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
    'nunst_color', {init_phase_StrDom.nunst, 5}, ...
    'add_2_gcf', 1)

%% plot folds weak
plot_branch3( fold_v_Weak, ...
    param, ...
    'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
    'color', 'r', ...
    'PlotStyle', { 'LineStyle', '-', 'Marker', '.' }, ...
    'add_2_gcf', 1)

%% plot phase before v
for i = 1:numel(phases_below_v_low)
    plot_branch3( phases_below_v_low{i}, ...
        param, ...
        'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
        'nunst_color', phases_below_v_low{i}.nunst, ...
        'add_2_gcf', 1)
end

%% Plot weak amp from unst and stab
for i = 1:numel(ampWeakDoms)
    plot_branch3( ampWeakDoms{i}, ...
        param, ...
        'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
        'nunst_color', ampWeakDoms{i}.nunst, ...
        'add_2_gcf', 1)
    pause(0.1)
end

%% Plot folds from weak amp
for i = 1:numel(foldsFromMidAmpWeakDom)
    plot_branch3( foldsFromMidAmpWeakDom{i}, ...
        param, ...
        'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
        'color', 'm', ...
        'PlotStyle', { 'LineStyle', '-', 'Marker', '.' }, ...
        'add_2_gcf', 1)
    pause(0.1)
end

%% plot folds strong
plot_branch3( fold_v_Str, ...
    param, ...
    'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
    'color', 'r', ...
    'PlotStyle', { 'LineStyle', '-', 'Marker', '.' }, ...
    'add_2_gcf', 1)

%% Plot strong amp
% this is the one which is very close to the loop, connects the two
plot_branch3( ampStrDom, ...
    param, ...
    'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
    'nunst_color', ampStrDom.nunst, ...
    'add_2_gcf', 1)

% %% The one which traces from strong dom down towards weak dom
% plot_branch3( unlikelyStableMidDom, ...
%     param, ...
%     'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
%     'nunst_color', unlikelyStableMidDom.nunst, ...
%     'add_2_gcf', 1)

%% Extra phase from Strong Dom, but near weak
plot_branch3( phaseAlongStrDoms{3}, ...
    param, ...
    'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
    'nunst_color', phaseAlongStrDoms{3}.nunst, ...
    'add_2_gcf', 1)

plot_branch3( phaseAlongStrDoms{4}, ...
    param, ...
    'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
    'nunst_color', phaseAlongStrDoms{4}.nunst, ...
    'add_2_gcf', 1)












%% Further phase continuations
% Low feed amp
% load vfolds

% parameter setup
par_below_v = setup_params_nonDim_CnstCplRatio(...
    'save',0, ...
    'J', current, ...
    'feed_ampli', 0.030, ...
    'feed_ampliMatrix', feedAmpMat, ...
    'feed_phase', 0, ...
    'feed_phaseMatrix', feedPhaseMat, ...
    'tau_fb', tau_fb_par, ...
    'alpha_par',alpha_par, ...
    'clear',0,...
    'populate_wrkspc', 0);

turn_on_below_v = turn_on(par_below_v, [1, 0, 1, 0, 0]);
% figure
% plot(turn_on_below_v.x, turn_on_below_v.y)

[amp_BelowV,~] = SetupStst( ...
    funcs, ...
    'contpar',[param.feed_ampli.index, param.omega1.index], ...
    'corpar',[param.omega1.index],...
    'x', turn_on_below_v.y(:,end), ...
    'parameter',par_below_v.values(1:end-1),...
    opt_inputs{:},...
    st_amp{:});

amp_BelowV = bcont( funcs, amp_BelowV, ...
                            50, 50 );
amp_BelowV = branch_stability(funcs, amp_BelowV);

pts = branch_pts_near_param( amp_BelowV, param.feed_ampli.index, 0, 0.009 );

[phases_below_v_low{3},~] = SetupStst( ...
        funcs, ...
        'contpar',[param.feed_phase.index, param.omega1.index], ...
        'corpar',[param.omega1.index],...
        'x', amp_BelowV.point(pts(1)).x, ...
        'parameter', amp_BelowV.point(pts(1)).parameter,...
        opt_inputs{:},...
        st_phase{:});

    phases_below_v_low{3} = bcont( funcs, phases_below_v_low{3}, ...
                                50, 50 );
    phases_below_v_low{3} = branch_stability(funcs, phases_below_v_low{3});


%% plot
figure;
for i = 1:numel(phases_below_v_low)
    plot_branch3( phases_below_v_low{i}, ...
        param, ...
        'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
        'nunst_color', phases_below_v_low{i}.nunst, ...
        'add_2_gcf', 1)
end

%% mid1 phase
pts = branch_pts_near_param( ampStrDom, ...
                       param.feed_ampli.index, ...
                       init_phase_StrDom.point(1).parameter(param.feed_ampli.index), ...
                       0.004 );
pts = pts(ampStrDom.nunst(pts) == 2);

[unst_phase_mid1,~] = SetupStst( ...
    funcs, ...
    'contpar',[param.feed_phase.index, param.omega1.index], ...
    'corpar',[param.omega1.index],...
    'x', ampStrDom.point(pts).x, ...
    'parameter',ampStrDom.point(pts).parameter,...
    opt_inputs{:},...
    st_phase{:});

unst_phase_mid1 = bcont( funcs, unst_phase_mid1, ...
                            200, 200 );
unst_phase_mid1 = branch_stability(funcs, unst_phase_mid1);



%% plot
figure;
plot_branch3( init_phase_StrDom, ...
    param, ...
    'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
    'nunst_color', init_phase_StrDom.nunst, ...
    'add_2_gcf', 1)

plot_branch3( unst_phase_mid1, ...
    param, ...
    'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
    'nunst_color', unst_phase_mid1.nunst, ...
    'add_2_gcf', 1)

plot_branch3( init_phase_WeakDom, ...
    param, ...
    'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
    'nunst_color', init_phase_WeakDom.nunst, ...
    'add_2_gcf', 1)

%% mid2 amp (gap between two parabola folds)
% in this case, I know it is close to 0.34

pts = branch_pts_near_param( ampWeakDoms{3}, ...
                       param.feed_ampli.index, ...
                       0.34, ...
                       0.004 );

mid2_phases = cell(1,numel(pts));

for i = 1:numel(pts)
    [mid2_phases{i},~] = SetupStst( ...
    funcs, ...
    'contpar',[param.feed_phase.index, param.omega1.index], ...
    'corpar',[param.omega1.index],...
    'x', ampWeakDoms{3}.point(pts(i)).x, ...
    'parameter',ampWeakDoms{3}.point(pts(i)).parameter,...
    opt_inputs{:},...
    st_amp{:});
    mid2_phases{i} = bcont( funcs, mid2_phases{i}, ...
                                200, 200 );
    mid2_phases{i} = branch_stability(funcs, mid2_phases{i});
end

%% plot
figure;
for i = 1:numel(mid2_phases)
    plot_branch3( mid2_phases{i}, ...
        param, ...
        'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
        'nunst_color', mid2_phases{i}.nunst, ...
        'add_2_gcf', 1)
end

%% high amp

% parameter setup
par_high = setup_params_nonDim_CnstCplRatio(...
    'save',0, ...
    'J', current, ...
    'feed_ampli', 0.36, ...
    'feed_ampliMatrix', feedAmpMat, ...
    'feed_phase', 0, ...
    'feed_phaseMatrix', feedPhaseMat, ...
    'tau_fb', tau_fb_par, ...
    'alpha_par',alpha_par, ...
    'clear',0,...
    'populate_wrkspc', 0);

turn_on_high = turn_on(par_high, [1, 0, 1, 0, 0]);

[phase_high,~] = SetupStst( ...
    funcs, ...
    'contpar',[param.feed_phase.index, param.omega1.index], ...
    'corpar',[param.omega1.index],...
    'x', turn_on_high.y(:,end), ...
    'parameter',par_high.values(1:end-1),...
    opt_inputs{:},...
    st_amp{:});

phase_high = bcont( funcs, phase_high, ...
                            400, 400 );
phase_high = branch_stability(funcs, phase_high);

%% plot
figure;
plot_branch3( phase_high, ...
    param, ...
    'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
    'nunst_color', phase_high.nunst, ...
    'add_2_gcf', 1)

%% extra fold?!
% it is the other parabola one
possible = [];
for i = 1:numel(phase_high.indFold)
    if phase_high.point(phase_high.indFold(i)).x(1) < 0.2
        possible(end+1) = phase_high.indFold(i);
    end
end
finds = intersect(destabilize_finder(phase_high.nunst), possible);

% WeakDom fold
[foldfuncs,highAmpFold,~]=SetupRWFold( ...
    funcs, ...
    phase_high, ...
    finds(1),...
    'contpar', ...
    [param.feed_phase.index, param.feed_ampli.index, param.omega1.index], ...
    'dir',param.feed_ampli.index, ...
    opt_inputs{:},...
    st_bif{:}); 

highAmpFold = bcont( foldfuncs, highAmpFold, 50, 50 );

%% plot
plot_branch3( highAmpFold, ...
    param, ...
    'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
    'color', 'r', ...
    'PlotStyle', { 'LineStyle', '-', 'Marker', '.' }, ...
    'add_2_gcf', 1)

%% vhigh amp

% parameter setup
par_vhigh = setup_params_nonDim_CnstCplRatio(...
    'save',0, ...
    'J', current, ...
    'feed_ampli', 0.38, ...
    'feed_ampliMatrix', feedAmpMat, ...
    'feed_phase', 0, ...
    'feed_phaseMatrix', feedPhaseMat, ...
    'tau_fb', tau_fb_par, ...
    'alpha_par',alpha_par, ...
    'clear',0,...
    'populate_wrkspc', 0);

turn_on_vhigh = turn_on(par_vhigh, [1, 0, 1, 0, 0]);

[phase_vhigh,~] = SetupStst( ...
    funcs, ...
    'contpar',[param.feed_phase.index, param.omega1.index], ...
    'corpar',[param.omega1.index],...
    'x', turn_on_vhigh.y(:,end), ...
    'parameter',par_vhigh.values(1:end-1),...
    opt_inputs{:},...
    st_amp{:});

phase_vhigh = bcont( funcs, phase_vhigh, ...
                            400, 400 );
phase_vhigh = branch_stability(funcs, phase_vhigh);

%% plot
figure;
plot_branch3( phase_vhigh, ...
    param, ...
    'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
    'nunst_color', phase_vhigh.nunst, ...
    'add_2_gcf', 1)


%% save everything
if 1
    % save location
    datadir = strcat(data_directory(), 'specific_bifurcations/');
    while isdir(datadir) == 0
        mkdir(datadir);
    end
    
    save(strcat(datadir, 'vfolds'))
end














%% Phase collection
% Folds

folds = {};

% increasing intensity
folds{1} = fold_v_Weak;
folds{end+1} = highAmpFold;
folds{end+1} = foldsFromMidAmpWeakDom{3};
folds{end+1} = foldsFromMidAmpWeakDom{2};
folds{end+1} = foldsFromMidAmpWeakDom{1};
folds{end+1} = fold_v_Str;



%% plot
figure;
for i = 1:numel(folds)
    plot_branch3( folds{i}, ...
    param, ...
    'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
    'color', 'r', ...
    'PlotStyle', { 'LineStyle', '-', 'Marker', '.' }, ...
    'add_2_gcf', 1)
end

%% Phases

phases = {};

% low
for i = 1:numel(phases_below_v_low)
    phases{end+1} = phases_below_v_low{i};
end

% low loops
phases{end+1} = init_phase_StrDom;
phases{end+1} = unst_phase_mid1;
phases{end+1} = init_phase_WeakDom;

% mid below double parabolas
for i = 1:numel(mid2_phases) - 1
    phases{end+1} = mid2_phases{i};
end

% mid between double parabolas
phases{end+1} = phase_high;

% high
phases{end+1} = phase_vhigh;

%% plot
figure
for i = 1:numel(phases)
    plot_branch3( phases{i}, ...
        param, ...
        'axes_indParam', {param.feed_phase.index, param.feed_ampli.index, 'x1'}, ...
        'nunst_color', phases{i}.nunst, ...
        'add_2_gcf', 1)
end

%% save just the collection
if 1
    % save location
    datadir = strcat(data_directory(), 'specific_bifurcations/');
    while isdir(datadir) == 0
        mkdir(datadir);
    end
    
    save(strcat(datadir, 'phase_collection'), ...
        'funcs', 'foldfuncs', 'phases', 'folds', 'param', ...
        'st_amp','st_phase', 'st_bif', 'opt_inputs')
end