%% For doing a new scan at a different fb amplitude
%% For strongDom fields AKA sweepup

% load
treeLoader('datadir_specific', ...
    '/home/bkmiller/qd-micropillar-laser-project/data_bimodal-qd-micropillars/zeroPhaseOffsetJ=560uA/strongDomAlpha=0/tau_fb=0.83ns/');


% more stst sweeps
stdyBrnchFB = steadyBranchMultiCreator( ...
    funcs,  ...
    [0.1, 0.2, 0.3, 0.4, 0.5, 0.6], ...
    param.feed_phase.index, ...
    300, ...
    param, ...
    'sweep',1);

save([master_options.datadir_specific,'stdyBrnchFB'],'stdyBrnchFB')


%% For weakDom fields aka no sweep
% treeLoader('datadir_specific', ...
%     '/home/bkmiller/qd-micropillar-laser-project/data_bimodal-qd-micropillars/zeroPhaseOffsetJ=560uA/weakDomAlpha=0/tau_fb=0.83ns/');
